stages:
  - build
  - deploy

.go_setup:
  variables:
    GOPATH: "$CI_PROJECT_DIR/.cache"
    GOLANGCI_LINT_CACHE: $CI_PROJECT_DIR/.golangci-lint
  before_script:
    - mkdir -p .cache
    - go mod vendor
  cache:
    key: "$CI_COMMIT_REF_NAME-golang-cache"
    paths:
      - .cache/pkg/mod

build binary:
  image: golang:latest
  stage: build
  tags:
    - amd64
  extends:
    - .go_setup
  script:
    - go build ./cmds/bot/main.go
  only:
    - master

deploy:bot:
  image: ubuntu:jammy
  stage: deploy
  tags:
    - production
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)

    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    - ssh-keyscan "$DOCKER_HOST_IP" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh "deploy@$DOCKER_HOST_IP" 'bash -s' < deploy/deploy-bot.sh
  only:
    - master
